#Requires -Version 5.1
<#
.SYNOPSIS
    Export YouTube cookies from Chrome to Netscape format for yt-dlp.
.DESCRIPTION
    Kills existing Chrome, starts new instance with remote debugging,
    extracts cookies via Chrome DevTools Protocol, writes cookies.txt.
#>

$ErrorActionPreference = "Continue"

$COOKIE_PATH = "$env:USERPROFILE\matt-wolfe-podcast\cookies.txt"
$CHROME_PATH = "C:\Program Files\Google\Chrome\Application\chrome.exe"
$CDP_PORT = 9222

Write-Host "[*] Killing Chrome processes..."
Get-Process chrome -ErrorAction SilentlyContinue | Stop-Process -Force
Start-Sleep -Seconds 3

Write-Host "[*] Starting Chrome with remote debugging..."
$chromeArgs = @(
    "--remote-debugging-port=$CDP_PORT",
    "--remote-allow-origins=*",
    "--no-first-run", "--no-default-browser-check",
    "--disable-sync", "--disable-background-networking",
    "--user-data-dir=$env:LOCALAPPDATA\Google\Chrome\User Data",
    "https://www.youtube.com"
)

$proc = Start-Process -FilePath $CHROME_PATH -ArgumentList $chromeArgs -PassThru
Write-Host "[*] Chrome PID: $($proc.Id)"

# Wait for CDP (up to 30s)
$wsUrl = $null
for ($i = 0; $i -lt 30; $i++) {
    Start-Sleep -Seconds 1
    try {
        $resp = Invoke-WebRequest -Uri "http://127.0.0.1:$CDP_PORT/json/version" -UseBasicParsing -TimeoutSec 2 -ErrorAction Stop
        $data = $resp.Content | ConvertFrom-Json
        $wsUrl = $data.webSocketDebuggerUrl
        Write-Host "[+] Chrome CDP ready: $($data.Browser)"
        break
    } catch { }
}

if (-not $wsUrl) {
    Write-Host "[!] Chrome CDP not ready"
    exit 1
}

# Use Python to get cookies via CDP (more reliable WebSocket handling)
$pythonCode = @'
import json, urllib.request, ssl, sys

# Get WebSocket URL from CDP
resp = urllib.request.urlopen("http://127.0.0.1:9222/json/version", timeout=5)
data = json.loads(resp.read())
ws_url = data["webSocketDebuggerUrl"]

# Connect WebSocket
import websocket
ws = websocket.create_connection(ws_url, timeout=10)

def send(method, params=None):
    msg = {"id": 1, "method": method}
    if params:
        msg["params"] = params
    ws.send(json.dumps(msg))
    while True:
        r = json.loads(ws.recv())
        if r.get("id") == 1:
            return r.get("result", {})

result = send("Network.getAllCookies")
ws.close()

all_cookies = result.get("cookies", [])
yt = [c for c in all_cookies if "youtube.com" in c.get("domain", "")]

if not yt:
    print("NO_COOKIES")
    sys.exit(1)

# Write Netscape format
lines = ["# Netscape HTTP Cookie File", "# Generated by Chrome CDP", ""]
for c in yt:
    domain = c.get("domain", ".youtube.com")
    domain_flag = "TRUE" if domain.startswith(".") else "FALSE"
    p = c.get("path", "/")
    secure = "TRUE" if c.get("secure", False) else "FALSE"
    httponly = "#HttpOnly_" if c.get("httpOnly", False) else ""
    expires = str(max(int(c.get("expires", 0)), 0))
    name = c.get("name", "")
    value = c.get("value", "")
    lines.append(f"{httponly}{domain}\t{domain_flag}\t{p}\t{secure}\t{expires}\t{name}\t{value}")

with open(r"COOKIE_PATH_PLACEHOLDER", "w", encoding="utf-8") as f:
    f.write("\n".join(lines) + "\n")

print(f"OK:{len(yt)}")
'@

# Replace placeholder with actual path
$pythonCode = $pythonCode.Replace("COOKIE_PATH_PLACEHOLDER", $COOKIE_PATH)

# Write Python script to temp file and execute
$tmpPy = [System.IO.Path]::GetTempFileName() + ".py"
[System.IO.File]::WriteAllText($tmpPy, $pythonCode, [System.Text.UTF8Encoding]::new($false))

Write-Host "[*] Running Python CDP client..."
$pyResult = & python $tmpPy 2>&1
$exitCode = $LASTEXITCODE

Remove-Item $tmpPy -Force -ErrorAction SilentlyContinue

if ($exitCode -eq 0 -and $pyResult -match "OK:(\d+)") {
    $count = $Matches[1]
    Write-Host "[+] Exported $count YouTube cookies to $COOKIE_PATH"
    Write-Host "[+] File size: $((Get-Item $COOKIE_PATH).Length) bytes"
    # Keep Chrome running for user
    exit 0
} else {
    Write-Host "[!] Python CDP failed: $pyResult"
    # Kill Chrome since we couldn't get cookies
    $proc.Kill() 2>$null
    exit 1
}
