#Requires -Version 5.1
<#
.SYNOPSIS
    Export YouTube cookies from Chrome to Netscape format for yt-dlp.
    Full automation using Chrome DevTools Protocol via .NET.
#>

$ErrorActionPreference = "Stop"
$COOKIE_PATH = "$env:USERPROFILE\matt-wolfe-podcast\cookies.txt"
$CHROME_PATH = "C:\Program Files\Google\Chrome\Application\chrome.exe"
$USER_DATA = "$env:LOCALAPPDATA\Google\Chrome\User Data"
$CDP_PORT = 9222

Write-Host "[1/4] Killing old Chrome..."
Get-Process chrome -ErrorAction SilentlyContinue | Stop-Process -Force
Start-Sleep -Seconds 3

Write-Host "[2/4] Starting Chrome with remote debugging..."
$proc = Start-Process -FilePath $CHROME_PATH -ArgumentList @(
    "--remote-debugging-port=$CDP_PORT",
    "--remote-allow-origins=*",
    "--no-first-run", "--no-default-browser-check",
    "--disable-gpu", "--no-sandbox",
    "--user-data-dir=$USER_DATA",
    "https://www.youtube.com"
) -PassThru

Write-Host "  PID=$($proc.Id)"

# Wait for CDP
Write-Host "[3/4] Waiting for CDP..."
$wsUrl = $null
for ($i = 0; $i -lt 60; $i++) {
    Start-Sleep -Seconds 1
    try {
        $resp = Invoke-WebRequest -Uri "http://127.0.0.1:$CDP_PORT/json/version" -UseBasicParsing -TimeoutSec 2 -ErrorAction Stop
        $data = $resp.Content | ConvertFrom-Json
        $wsUrl = $data.webSocketDebuggerUrl
        Write-Host "  CDP ready after ${i}s"
        break
    } catch { }
}

if (-not $wsUrl) {
    Write-Host "  ERROR: Chrome CDP not ready after 60s"
    $proc.Kill() 2>$null
    exit 1
}

# Get cookies via temporary Python script (more reliable than PowerShell WebSocket)
Write-Host "[4/4] Extracting YouTube cookies..."
$tmpPy = [System.IO.Path]::GetTempFileName() + ".py"

$pythonCode = @'
import json, urllib.request, sys
import websocket
try:
    resp = urllib.request.urlopen("http://127.0.0.1:9222/json/version", timeout=5)
    ws_url = json.loads(resp.read())["webSocketDebuggerUrl"]
    ws = websocket.create_connection(ws_url, timeout=10)
    ws.send(json.dumps({"id": 1, "method": "Network.getAllCookies"}))
    while True:
        r = json.loads(ws.recv())
        if r.get("id") == 1:
            cookies = r["result"].get("cookies", [])
            break
    ws.close()
    yt = [c for c in cookies if "youtube.com" in c.get("domain", "")]
    print(json.dumps({"count": len(yt), "cookies": yt}))
except Exception as e:
    print(json.dumps({"error": str(e)}))
    sys.exit(1)
'@

[System.IO.File]::WriteAllText($tmpPy, $pythonCode)
$pyResult = & python $tmpPy 2>&1
$rc = $LASTEXITCODE
Remove-Item $tmpPy -Force -ErrorAction SilentlyContinue

if ($rc -ne 0) {
    Write-Host "  ERROR: Python CDP failed"
    $proc.Kill() 2>$null
    exit 1
}

$result = $pyResult | ConvertFrom-Json
$count = $result.count
$cookiesList = $result.cookies

Write-Host "  Found $count YouTube cookies"

if ($count -eq 0) {
    Write-Host "  WARNING: No YouTube cookies found (not logged in?)"
    $proc.Kill() 2>$null
    exit 1
}

# Write Netscape format cookies
$lines = @(
    "# Netscape HTTP Cookie File",
    "# Generated by export_cookies.ps1",
    ""
)

foreach ($c in $cookiesList) {
    $domain = $c.domain
    $df = if ($domain.StartsWith(".")) { "TRUE" } else { "FALSE" }
    $sf = if ($c.secure) { "TRUE" } else { "FALSE" }
    $hf = if ($c.httpOnly) { "#HttpOnly_" } else { "" }
    $exp = [Math]::Max([int]($c.expires), 0)
    $lines += "$hf$domain`t$df`t$($c.path)`t$sf`t$exp`t$($c.name)`t$($c.value)"
}

[System.IO.File]::WriteAllLines($COOKIE_PATH, $lines, [System.Text.UTF8Encoding]::new($false))
Write-Host "  Written to $COOKIE_PATH ($((Get-Item $COOKIE_PATH).Length) bytes)"

# Verify
$essential = @("SAPISID", "APISID", "SSID", "HSID", "SID")
$foundEssential = $cookiesList | Where-Object { $_.name -in $essential } | Select-Object -ExpandProperty name
Write-Host "  Essential cookies: $($foundEssential.Count)/$($essential.Count)"

exit 0
