"""
YouTube Cookie 刷新工具

用法：
  自动模式:  python refresh_cookies.py
             尝试通过 CDP 自动提取（可能受限于环境）

  手动模式:  python refresh_cookies.py --manual
             打开 Chrome 并指导你手动导出 cookies

cookies 过期时，pipeline 会自动调用此脚本。
"""

import argparse
import logging
import os
import subprocess
import sys
import time

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
log = logging.getLogger(__name__)

COOKIE_PATH = os.path.join(os.path.dirname(__file__), "cookies.txt")


def try_cdp_auto():
    """尝试通过 CDP 自动获取 cookies（在部分环境中可能失败）。"""
    import urllib.request, json, websocket

    CHROME_PATH = r"C:\Program Files\Google\Chrome\Application\chrome.exe"
    USER_DATA = os.path.expanduser("~/AppData/Local/Google/Chrome/User Data")

    # 杀掉旧 Chrome，重新启动
    subprocess.run(["taskkill", "/F", "/IM", "chrome.exe"], capture_output=True)
    time.sleep(3)

    proc = subprocess.Popen(
        [CHROME_PATH,
         "--remote-debugging-port=9222",
         "--remote-allow-origins=*",
         "--no-first-run",
         "--no-default-browser-check",
         f"--user-data-dir={USER_DATA}",
         "https://www.youtube.com"],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        creationflags=subprocess.CREATE_NEW_PROCESS_GROUP,
    )
    log.info("Chrome started (PID=%d), waiting for CDP...", proc.pid)

    # 最多等 60 秒
    for i in range(60):
        time.sleep(1)
        try:
            resp = urllib.request.urlopen("http://127.0.0.1:9222/json/version", timeout=2)
            data = json.loads(resp.read())
            log.info("CDP ready after %ds!", i + 1)
            ws_url = data["webSocketDebuggerUrl"]
            break
        except Exception:
            continue
    else:
        log.warning("CDP not available after 60s")
        proc.kill()
        return False

    # 获取 cookies
    ws = websocket.create_connection(ws_url, timeout=10)
    ws.send(json.dumps({"id": 1, "method": "Network.getAllCookies"}))
    while True:
        r = json.loads(ws.recv())
        if r.get("id") == 1:
            cookies = r.get("result", {}).get("cookies", [])
            break
    ws.close()

    yt = [c for c in cookies if "youtube.com" in c.get("domain", "")]
    if not yt:
        log.warning("No YouTube cookies found (not logged in?)")
        proc.kill()
        return False

    _write_cookies(yt)
    log.info("CDP 自动提取成功! 导出 %d 个 YouTube cookies", len(yt))
    proc.kill()
    return True


def do_manual_export():
    """手动模式：打开 Chrome 并指导用户导出 cookies。"""
    print()
    print("=" * 60)
    print("  Cookie 手动导出指南")
    print("=" * 60)
    print()
    print("即将打开 Chrome 到 YouTube...")
    print()

    # 打开 Chrome
    chrome = r"C:\Program Files\Google\Chrome\Application\chrome.exe"
    if os.path.isfile(chrome):
        subprocess.Popen([chrome, "https://www.youtube.com"])
    else:
        subprocess.Popen(["start", "https://www.youtube.com"], shell=True)

    print("请按以下步骤操作：")
    print()
    print("  1. 确保已登录 YouTube")
    print("  2. 点击地址栏右侧的 Get cookies.txt 扩展图标")
    print("  3. 点击 Export 按钮")
    print("  4. 将下载的文件保存/复制到：")
    print(f"      {COOKIE_PATH}")
    print()
    print("完成后，在此终端输入 y 并回车确认：", end="")
    sys.stdout.flush()

    # 等待用户确认
    try:
        response = input().strip().lower()
        if response == "y":
            if os.path.isfile(COOKIE_PATH) and os.path.getsize(COOKIE_PATH) > 100:
                print(f"\nOK! cookies.txt ({os.path.getsize(COOKIE_PATH)} bytes)")
                return True
            else:
                print(f"\n❌ 未检测到 cookies.txt，请检查文件路径")
                return False
        else:
            print("\n已取消")
            return False
    except (EOFError, KeyboardInterrupt):
        print("\n已取消")
        return False


def _write_cookies(cookies):
    """写入 Netscape 格式 cookies.txt"""
    lines = [
        "# Netscape HTTP Cookie File",
        f"# Generated by refresh_cookies.py at {time.strftime('%Y-%m-%d %H:%M:%S')}",
        "",
    ]
    for c in cookies:
        domain = c.get("domain", ".youtube.com")
        df = "TRUE" if domain.startswith(".") else "FALSE"
        httponly = "#HttpOnly_" if c.get("httpOnly", False) else ""
        lines.append(
            f'{httponly}{domain}\t{df}\t{c.get("path","/")}\t'
            f'{"TRUE" if c.get("secure") else "FALSE"}\t'
            f'{max(int(c.get("expires",0)),0)}\t'
            f'{c.get("name","")}\t{c.get("value","")}'
        )
    with open(COOKIE_PATH, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def verify_cookies():
    """快速验证 cookies 是否有效。"""
    try:
        import subprocess
        result = subprocess.run(
            [sys.executable, "-m", "yt_dlp",
             "--cookies", COOKIE_PATH,
             "--skip-download", "--print", "title",
             "https://www.youtube.com/watch?v=Db260rUuKJg"],
            capture_output=True, text=True, timeout=30,
        )
        if "Sign in" not in result.stderr and result.returncode == 0:
            return True
        return False
    except Exception:
        return False


def main():
    parser = argparse.ArgumentParser(description="YouTube Cookie 刷新工具")
    parser.add_argument("--manual", action="store_true", help="手动导出模式")
    args = parser.parse_args()

    if args.manual:
        success = do_manual_export()
    else:
        print("尝试 CDP 自动提取...")
        success = try_cdp_auto()
        if not success:
            print("\n⚠️  CDP 自动提取失败，切换到手动模式")
            print("   这是因为 Git Bash 环境无法启动 Chrome 调试端口")
            success = do_manual_export()

    # 验证 cookies
    if success and os.path.isfile(COOKIE_PATH):
        if verify_cookies():
            print("\n✅ Cookie 验证通过! yt-dlp 可以正常使用")
        else:
            print("\n⚠️  Cookie 文件已保存但验证未通过（可能已过期）")

    return 0 if success else 1


if __name__ == "__main__":
    sys.exit(main())
