"""
Chrome Cookie Auto-Exporter

策略链（从高到低优先级）：
1. PowerShell CDP — 最可靠，通过 PowerShell 启动 Chrome + DevTools Protocol
2. Selenium — 次选
3. browser_cookie3 — 最终尝试

PowerShell CDP 方案说明：
- 调用 export_cookies.ps1 启动 Chrome 并获取 cookies（全程自动化）
- 在 PowerShell 中完成所有操作（避免 Git Bash 上下文问题）
"""

import json
import logging
import os
import subprocess
import sys
import time

logger = logging.getLogger(__name__)

COOKIE_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "cookies.txt")


def _write_netscape_cookies(cookies: list, path: str) -> int:
    """Write cookies in Netscape HTTP Cookie File format (for yt-dlp)."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by cookie_helper.py",
        "",
    ]
    for c in cookies:
        domain = c.get("domain", ".youtube.com")
        domain_flag = "TRUE" if domain.startswith(".") else "FALSE"
        p = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        httponly = "#HttpOnly_" if c.get("httpOnly", False) else ""
        expires = str(max(int(c.get("expires", 0)), 0))
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(
            f"{httponly}{domain}\t{domain_flag}\t{p}\t{secure}\t{expires}\t{name}\t{value}"
        )
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return len(cookies)


def _export_via_cdp_powershell() -> bool:
    """
    通过 PowerShell 启动 Chrome CDP 并导出 cookies.

    这是最可靠的方案，因为 PowerShell 有完整的 Windows API 访问权限。
    """
    ps_script = os.path.join(os.path.dirname(os.path.dirname(__file__)), "export_cookies.ps1")
    if not os.path.isfile(ps_script):
        logger.error("PowerShell script not found: %s", ps_script)
        return False

    try:
        result = subprocess.run(
            ["powershell", "-ExecutionPolicy", "Bypass", "-File", ps_script],
            capture_output=True, text=True, timeout=120,
        )
        logger.info("PowerShell output: %s", result.stdout[-500:])
        if result.stderr:
            logger.debug("PowerShell stderr: %s", result.stderr[-300:])

        if os.path.isfile(COOKIE_PATH) and os.path.getsize(COOKIE_PATH) > 100:
            logger.info("CDP PowerShell: exported %d bytes", os.path.getsize(COOKIE_PATH))
            return True

        logger.warning("CDP PowerShell failed")
        return False

    except subprocess.TimeoutExpired:
        logger.warning("CDP PowerShell timed out")
        return False
    except Exception as exc:
        logger.warning("CDP PowerShell error: %s", exc)
        return False


def _export_via_selenium() -> bool:
    """使用 Selenium WebDriver. 可能无法在 Git Bash 中工作."""
    from selenium import webdriver
    from selenium.webdriver.chrome.options import Options

    user_data = os.path.expanduser("~/AppData/Local/Google/Chrome/User Data")
    options = Options()
    options.add_argument(f"--user-data-dir={user_data}")
    options.add_argument("--profile-directory=Default")
    options.add_argument("--remote-allow-origins=*")
    options.add_argument("--headless=new")
    options.page_load_strategy = "eager"

    try:
        driver = webdriver.Chrome(options=options)
        driver.get("https://www.youtube.com")
        time.sleep(2)
        cookies = driver.get_cookies()
        driver.quit()
        yt = [c for c in cookies if "youtube.com" in c.get("domain", "")]
        count = _write_netscape_cookies(yt or cookies, COOKIE_PATH)
        logger.info("Selenium: exported %d cookies", count)
        return True
    except Exception as exc:
        logger.warning("Selenium failed: %s", exc)
        return False


def _export_via_browser_cookie3() -> bool:
    """使用 browser_cookie3 直接读取数据库（需要管理员权限或 Chrome v10 格式）。"""
    try:
        import browser_cookie3
        cj = browser_cookie3.chrome(domain_name="youtube.com")
        cookies = list(cj)
        if not cookies:
            return False
        c_list = [{
            "domain": c.domain, "name": c.name, "value": c.value,
            "path": c.path, "secure": c.secure,
            "httpOnly": c.get_nonstandard_attr("httponly", False),
            "expires": c.expires or 0,
        } for c in cookies]
        count = _write_netscape_cookies(c_list, COOKIE_PATH)
        logger.info("browser_cookie3: exported %d cookies", count)
        return True
    except Exception as exc:
        logger.warning("browser_cookie3 failed: %s", exc)
        return False


def auto_refresh_cookies() -> bool:
    """
    自动刷新 YouTube cookies，供 yt-dlp 使用。

    策略链：
    1. PowerShell CDP（最可靠，Windows 原生支持）
    2. Selenium WebDriver（次选）
    3. browser_cookie3（最后尝试）

    Returns:
        True if any strategy succeeded.
    """
    logger.info("自动刷新 YouTube cookies...")

    strategies = [
        ("PowerShell CDP", _export_via_cdp_powershell),
        ("Selenium", _export_via_selenium),
        ("browser_cookie3", _export_via_browser_cookie3),
    ]

    for name, fn in strategies:
        logger.info("尝试策略: %s", name)
        try:
            if fn():
                size = os.path.getsize(COOKIE_PATH) if os.path.isfile(COOKIE_PATH) else 0
                logger.info("%s 成功! cookies.txt (%d bytes)", name, size)
                return True
        except Exception as exc:
            logger.warning("%s 异常: %s", name, exc)

    logger.error("所有 cookie 导出策略均失败")
    return False


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )
    success = auto_refresh_cookies()
    status = "✅ SUCCESS" if success else "❌ FAILED"
    print(f"\n{status}: cookies exported to {COOKIE_PATH}")
    if os.path.isfile(COOKIE_PATH):
        print(f"   File size: {os.path.getsize(COOKIE_PATH)} bytes")
    sys.exit(0 if success else 1)
