"""
Chrome Cookie Auto-Exporter

策略链（从高到低优先级）：
1. PowerShell CDP — 最可靠，通过 PowerShell 启动 Chrome + DevTools Protocol
2. Selenium — 次选
3. browser_cookie3 — 最终尝试

PowerShell CDP 方案说明：
- 调用 export_cookies.ps1 启动 Chrome 并获取 cookies（全程自动化）
- 在 PowerShell 中完成所有操作（避免 Git Bash 上下文问题）
"""

import json
import logging
import os
import subprocess
import sys
import time

logger = logging.getLogger(__name__)

COOKIE_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "cookies.txt")


def _file_md5(path: str) -> str:
    """Get MD5 hash of a file."""
    import hashlib
    h = hashlib.md5()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def _write_netscape_cookies(cookies: list, path: str) -> int:
    """Write cookies in Netscape HTTP Cookie File format (for yt-dlp)."""
    lines = [
        "# Netscape HTTP Cookie File",
        "# Generated by cookie_helper.py",
        "",
    ]
    for c in cookies:
        domain = c.get("domain", ".youtube.com")
        domain_flag = "TRUE" if domain.startswith(".") else "FALSE"
        p = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        httponly = "#HttpOnly_" if c.get("httpOnly", False) else ""
        expires = str(max(int(c.get("expires", 0)), 0))
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(
            f"{httponly}{domain}\t{domain_flag}\t{p}\t{secure}\t{expires}\t{name}\t{value}"
        )
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return len(cookies)


def _export_via_cdp_powershell() -> bool:
    """
    通过 Python 直接启动 Chrome CDP 并导出 cookies.

    这是最可靠的方案：
    1. 关闭旧 Chrome
    2. 用真实用户配置启动 Chrome + CDP
    3. 通过 DevTools Protocol 提取 cookies
    4. 保存为 cookies.txt
    """
    refresh_script = os.path.join(os.path.dirname(os.path.dirname(__file__)), "refresh_cookies.py")
    if not os.path.isfile(refresh_script):
        logger.error("refresh_cookies.py not found")
        return False

    try:
        # Record file state BEFORE running
        old_mtime = os.path.getmtime(COOKIE_PATH) if os.path.isfile(COOKIE_PATH) else 0
        old_size = os.path.getsize(COOKIE_PATH) if os.path.isfile(COOKIE_PATH) else 0
        old_md5 = _file_md5(COOKIE_PATH) if os.path.isfile(COOKIE_PATH) else ""

        result = subprocess.run(
            [sys.executable, refresh_script],
            capture_output=True, text=True, timeout=120,
        )
        stdout = result.stdout.strip()
        stderr = result.stderr.strip()

        if stdout:
            for line in stdout.splitlines():
                logger.info("refresh: %s", line)
        if stderr:
            for line in stderr.splitlines()[-5:]:
                logger.debug("refresh stderr: %s", line)

        new_md5 = _file_md5(COOKIE_PATH) if os.path.isfile(COOKIE_PATH) else ""

        if new_md5 and new_md5 != old_md5:
            new_size = os.path.getsize(COOKIE_PATH)
            logger.info("Cookies refreshed (%d -> %d bytes, md5 changed)", old_size, new_size)
            return True

        if result.returncode == 0 and "SUCCESS" in stdout:
            logger.info("Script reported SUCCESS (file may have same content)")
            return True

        logger.warning("Cookie refresh script returned code %d", result.returncode)
        return False

    except subprocess.TimeoutExpired:
        logger.warning("Cookie refresh timed out")
        return False
    except Exception as exc:
        logger.warning("Cookie refresh error: %s", exc)
        return False

    except subprocess.TimeoutExpired:
        logger.warning("CDP PowerShell timed out")
        return False
    except Exception as exc:
        logger.warning("CDP PowerShell error: %s", exc)
        return False


def _export_via_selenium() -> bool:
    """使用 Selenium WebDriver. 可能无法在 Git Bash 中工作."""
    from selenium import webdriver
    from selenium.webdriver.chrome.options import Options

    user_data = os.path.expanduser("~/AppData/Local/Google/Chrome/User Data")
    options = Options()
    options.add_argument(f"--user-data-dir={user_data}")
    options.add_argument("--profile-directory=Default")
    options.add_argument("--remote-allow-origins=*")
    options.add_argument("--headless=new")
    options.page_load_strategy = "eager"

    try:
        driver = webdriver.Chrome(options=options)
        driver.get("https://www.youtube.com")
        time.sleep(2)
        cookies = driver.get_cookies()
        driver.quit()
        yt = [c for c in cookies if "youtube.com" in c.get("domain", "")]
        count = _write_netscape_cookies(yt or cookies, COOKIE_PATH)
        logger.info("Selenium: exported %d cookies", count)
        return True
    except Exception as exc:
        logger.warning("Selenium failed: %s", exc)
        return False


def _export_via_browser_cookie3() -> bool:
    """使用 browser_cookie3 直接读取数据库（需要管理员权限或 Chrome v10 格式）。"""
    try:
        import browser_cookie3
        cj = browser_cookie3.chrome(domain_name="youtube.com")
        cookies = list(cj)
        if not cookies:
            return False
        c_list = [{
            "domain": c.domain, "name": c.name, "value": c.value,
            "path": c.path, "secure": c.secure,
            "httpOnly": c.get_nonstandard_attr("httponly", False),
            "expires": c.expires or 0,
        } for c in cookies]
        count = _write_netscape_cookies(c_list, COOKIE_PATH)
        logger.info("browser_cookie3: exported %d cookies", count)
        return True
    except Exception as exc:
        logger.warning("browser_cookie3 failed: %s", exc)
        return False


def auto_refresh_cookies() -> bool:
    """
    自动刷新 YouTube cookies，供 yt-dlp 使用。

    策略链：
    1. PowerShell CDP（最可靠，Windows 原生支持）
    2. Selenium WebDriver（次选）
    3. browser_cookie3（最后尝试）

    Returns:
        True if any strategy succeeded.
    """
    logger.info("自动刷新 YouTube cookies...")

    strategies = [
        ("PowerShell CDP", _export_via_cdp_powershell),
        ("Selenium", _export_via_selenium),
        ("browser_cookie3", _export_via_browser_cookie3),
    ]

    for name, fn in strategies:
        logger.info("尝试策略: %s", name)
        try:
            if fn():
                size = os.path.getsize(COOKIE_PATH) if os.path.isfile(COOKIE_PATH) else 0
                logger.info("%s 成功! cookies.txt (%d bytes)", name, size)
                return True
        except Exception as exc:
            logger.warning("%s 异常: %s", name, exc)

    logger.error("所有 cookie 导出策略均失败")
    return False


if __name__ == "__main__":
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
    )
    success = auto_refresh_cookies()
    status = "✅ SUCCESS" if success else "❌ FAILED"
    print(f"\n{status}: cookies exported to {COOKIE_PATH}")
    if os.path.isfile(COOKIE_PATH):
        print(f"   File size: {os.path.getsize(COOKIE_PATH)} bytes")
    sys.exit(0 if success else 1)
