"""
Chrome Cookie Auto-Exporter
通过 Chrome DevTools Protocol (CDP) 从用户真实 Chrome 配置中提取 cookies
"""

import json
import logging
import os
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.request

logger = logging.getLogger(__name__)

COOKIE_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "cookies.txt")
CHROME_USER_DATA = os.path.expanduser("~/AppData/Local/Google/Chrome/User Data")
CHROME_EXE = r"C:\Program Files\Google\Chrome\Application\chrome.exe"
CDP_PORT = 9222


def _find_chrome() -> str | None:
    """Find Chrome executable."""
    candidates = [
        CHROME_EXE,
        os.path.expanduser(r"~\AppData\Local\Google\Chrome\Application\chrome.exe"),
        r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
    ]
    for p in candidates:
        if os.path.isfile(p):
            return p
    return None


def _cdp_get_cookies(port: int) -> list:
    """通过 CDP WebSocket 获取 YouTube cookies"""
    import websocket

    resp = urllib.request.urlopen(f"http://127.0.0.1:{port}/json/version", timeout=5)
    data = json.loads(resp.read())
    ws_url = data["webSocketDebuggerUrl"]

    ws = websocket.create_connection(ws_url, timeout=10)
    msg_id = 1

    def send(method, params=None):
        nonlocal msg_id
        mid = msg_id
        msg_id += 1
        msg = {"id": mid, "method": method}
        if params:
            msg["params"] = params
        ws.send(json.dumps(msg))
        while True:
            resp_data = json.loads(ws.recv())
            if resp_data.get("id") == mid:
                return resp_data.get("result", {})

    # 获取所有 cookies，然后过滤 YouTube
    result = send("Network.getAllCookies")
    ws.close()
    all_cookies = result.get("cookies", [])
    return [c for c in all_cookies if "youtube.com" in c.get("domain", "")]


def _write_netscape_cookies(cookies: list[dict], path: str) -> int:
    """写入 Netscape 格式 cookie 文件"""
    lines = [
        "# Netscape HTTP Cookie File",
        f"# Generated by cookie_helper.py",
        "",
    ]
    for c in cookies:
        domain = c.get("domain", ".youtube.com")
        domain_flag = "TRUE" if domain.startswith(".") else "FALSE"
        path_val = c.get("path", "/")
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        httponly = "#HttpOnly_" if c.get("httpOnly", False) else ""
        expires = str(max(int(c.get("expires", 0)), 0))
        name = c.get("name", "")
        value = c.get("value", "")
        lines.append(f"{httponly}{domain}\t{domain_flag}\t{path_val}\t{secure}\t{expires}\t{name}\t{value}")

    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return len(cookies)


def export_via_cdp() -> bool:
    """
    通过 Chrome DevTools Protocol 导出 cookies。

    策略：
    1. 尝试连接已有 Chrome 的 CDP（用户手动启动的）
    2. 否则用用户真实配置启动 Chrome CDP
    """
    chrome = _find_chrome()
    if not chrome:
        logger.error("Chrome not found")
        return False

    # 策略 1: 先看看有没有已有的 CDP 端口
    try:
        cookies = _cdp_get_cookies(CDP_PORT)
        if cookies:
            n = _write_netscape_cookies(cookies, COOKIE_PATH)
            logger.info("Connected to existing CDP, exported %d YouTube cookies", n)
            return True
    except Exception:
        pass

    # 策略 2: 杀掉旧 Chrome，用用户配置启动 CDP
    logger.info("Killing old Chrome and starting with remote debugging...")
    subprocess.run(["taskkill", "/F", "/IM", "chrome.exe"],
                   capture_output=True, text=True)
    time.sleep(2)

    # 用用户真实配置启动 Chrome
    proc = subprocess.Popen(
        [chrome, f"--remote-debugging-port={CDP_PORT}",
         "--remote-allow-origins=*",
         "--no-first-run", "--no-default-browser-check",
         f"--user-data-dir={CHROME_USER_DATA}",
         "https://www.youtube.com"],
        stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
    )

    # 等待 CDP 就绪（最多 15 秒）
    for i in range(15):
        time.sleep(1)
        try:
            cookies = _cdp_get_cookies(CDP_PORT)
            if cookies:
                n = _write_netscape_cookies(cookies, COOKIE_PATH)
                logger.info("Exported %d YouTube cookies", n)
                return True
        except Exception:
            continue

    logger.warning("CDP did not become ready or no cookies found")
    return False


def auto_refresh_cookies() -> bool:
    """自动刷新 cookies"""
    return export_via_cdp()


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
    success = auto_refresh_cookies()
    print(f"{'SUCCESS' if success else 'FAILED'}: cookies exported to {COOKIE_PATH}")
    sys.exit(0 if success else 1)
